version: 0.2

phases:
  pre_build:
    commands:
      - aws --version
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 896200776730.dkr.ecr.ap-northeast-1.amazonaws.com
      - REPOSITORY_URI=896200776730.dkr.ecr.ap-northeast-1.amazonaws.com/nginx
      - IMAGE_TAG=nginx
  build:
    commands:
      - docker build -t $IMAGE_TAG:latest .
      - docker tag $IMAGE_TAG:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"nginx","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json